routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('/students', 'StudentController');
    Route::get('/file-upload', 'StudentController@fileUpload')->name('file-upload');
    Route::post('/upload', 'StudentController@upload')->name('upload');
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model {

    protected $table = 'students';
    protected $fillable = [
        'class_room_id',
        'teacher_id',
        'firstname',
        'lastname',
        'gender_id',
        'joined_year',
    ];

    public function gender() {
        return $this->hasOne(Gender::class, 'id', 'gender_id');
    }

    public function classRoom() {
        return $this->hasOne(ClassRoom::class, 'id', 'class_room_id');
    }

    public function teacher() {
        return $this->hasOne(Teacher::class, 'id', 'teacher_id');
    }

    /**
     * 
     * get location language wise
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public static function storeData($fileData, $groupId) {

        try {

            $csv_data = json_decode($fileData->data, true);

            unset($csv_data[0]);

            $result = $data = array();
            foreach ($csv_data as $rows) {

                $class_room = $rows[0];
                $teacher_name = $rows[1];
                $firstname = $rows[2];
                $lastname = $rows[3];
                $gender = $rows[4];
                $joined_year = $rows[5];

                $class_room_model = ClassRoom::where('name', $class_room)->first(['id']);
                $class_room_id = isset($class_room_model) ? $class_room_model->id : 0;

                $teacher_model = Teacher::where('name', $teacher_name)->first(['id']);
                $teacher_id = isset($teacher_model) ? $teacher_model->id : 0;

                $gender_model = Gender::where('code', $gender)->first(['id']);
                $gender_id = isset($gender_model) ? $gender_model->id : 0;

                $data['class_room_id'] = $class_room_id;
                $data['teacher_id'] = $teacher_id;
                $data['firstname'] = $firstname;
                $data['lastname'] = $lastname;
                $data['gender_id'] = $gender_id;
                $data['joined_year'] = $joined_year;
                $data['created_at'] = now();
                $data['updated_at'] = now();

                $result[] = $data;
            }
            Student::insert($result);
            return true;
        } catch (\Exception $ex) {

            return redirect()->back()->withErrors([$ex->getMessage()]);
        }

        return false;
    }

}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CsvImportRequest;
use Maatwebsite\Excel\Facades\Excel;
use App\FileInfo;
use App\ClassRoom;
use App\Teacher;
use App\Gender;
use App\Student;

class StudentController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $students = Student::latest('id', 'asc')->paginate(5);

        return view('students.index', compact('students'))
                        ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {

        $classrooms = ClassRoom::pluck('name', 'id');
        $teachers = Teacher::pluck('name', 'id');
        $genders = Gender::pluck('name', 'id');

        $years = [];
        $now_year = date('Y');
        for ($year = 2000; $year <= $now_year; $year++)
            $years[$year] = $year;

        return view('students.create', compact('classrooms', 'teachers', 'genders', 'years'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

        $request->validate([
            'class_room_id' => 'required|integer',
            'teacher_id' => 'required|integer',
            'firstname' => 'required|string',
            'lastname' => 'required|string',
            'gender_id' => 'required|integer',
            'joined_year' => 'required',
        ]);

        Student::create($request->all());

        return redirect()->route('students.index')
                        ->with(['success' => __('school/common.record_added_successfully')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student) {
        $student->delete();

        return redirect()->route('students.index')
                        ->with(['success' => __('school/common.record_deleted_successfully')]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student) {

        $classrooms = ClassRoom::pluck('name', 'id');
        $teachers = Teacher::pluck('name', 'id');
        $genders = Gender::pluck('name', 'id');

        $years = [];
        $now_year = date('Y');
        for ($year = 2000; $year <= $now_year; $year++)
            $years[$year] = $year;

        return view('students.edit', compact('classrooms', 'teachers', 'genders', 'student', 'years'));
    }

    /**
     * Edit student records
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student) {

        request()->validate([
            'class_room_id' => 'required|integer',
            'teacher_id' => 'required|integer',
            'firstname' => 'required|string',
            'lastname' => 'required|string',
            'gender_id' => 'required|integer',
            'joined_year' => 'required',
        ]);


        $student->update($request->all());
        return redirect()->route('students.index')
                        ->with(['success' => __('school/common.record_updated_successfully')]);
    }

    /**
     * Display the upload view.
     *
     * @return \Illuminate\Http\Response
     */
    public function fileUpload() {

        return view('students.upload');
    }

    /**
     * 
     * import CSV file data
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function upload(CsvImportRequest $request) {

        try {
            $path = $request->file('csv_file')->getRealPath();

            if ($request->has('header')) {
                $data = Excel::load($path, function($reader) {
                            
                        })->get()->toArray();
            } else {
                $data = array_map('str_getcsv', file($path));
            }

            if (count($data) > 0) {

                $csvDataFile = FileInfo::create([
                            'filename' => $request->file('csv_file')->getClientOriginalName(),
                            'file_header' => $request->has('header'),
                            'data' => json_encode($data)
                ]);


                $storeData = Student::storeData($csvDataFile, $request->id);

                if ($storeData) {
                    return redirect()->action('StudentController@index')->with(['success' => __('school/common.record_added_successfully')]);
                } else {

                    return redirect()->back()->withErrors(__('school/common.record_failed_to_add'));
                }
            } else {
                return redirect()->back();
            }
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors([$ex->getMessage()]);
        }
    }

}

resources/views/students/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div><br />
    @endif
    <div class="panel-heading">{{ __('school/common.add_students') }}</div>
    <div class="panel">
        <div class="panel-body bg-panel">
            <div class="row">
                {!! Form::open(['route' => 'students.store']) !!}
                <div class="col-xs-12 col-sm-12 col-md-6">

                    <div class="form-group">
                        {!! Form::Label('class_room_id', 'Class room:') !!}
                        {!! Form::select('class_room_id',$classrooms, ['class' => 'form-control']) !!}

                    </div>

                    <div class="form-group">
                        {!! Form::Label('teacher_id', 'Teacher`s name:') !!}
                        {!! Form::select('teacher_id',$teachers, ['class' => 'form-control']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::Label('firstname', 'Student`s first name:') !!}
                        {!! Form::text('firstname', null, ['class' => 'form-control']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::Label('lastname', 'Student`s last name:') !!}
                        {!! Form::text('lastname', null, ['class' => 'form-control']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::Label('gender_id', 'Gender:') !!}
                        {!! Form::select('gender_id',$genders, ['class' => 'form-control']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::Label('joined_year', 'Joined year:') !!}
                        {!! Form::select('joined_year', $years,['class' => 'form-control']) !!}
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>

                <input type="hidden" value="{{csrf_token()}}" name="_token" />
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/students/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div><br />
    @endif
    <div class="panel-heading">{{ __('school/common.update_students') }}</div>
    <div class="panel">
        <div class="panel-body bg-panel">
            <div class="row">
                {{ Form::model( $student, ['route' => ['students.update', $student->id], 'method' => 'put', 'role' => 'form'] ) }}

                <div class="col-xs-12 col-sm-12 col-md-6">

                    <div class="form-group">
                        {!! Form::Label('class_room_id', 'Class room:') !!}
                        {!! Form::select('class_room_id',$classrooms, ['class' => 'form-control']) !!}

                    </div>
                    <div class="form-group">
                        {!! Form::Label('teacher_id', 'Teacher`s name:') !!}
                        {!! Form::select('teacher_id',$teachers,$student->teacher_id, ['class' => 'form-control']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::Label('firstname', 'Student`s first name:') !!}
                        {!! Form::text('firstname', $student->firstname, ['class' => 'form-control']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::Label('lastname', 'Student`s last name:') !!}
                        {!! Form::text('lastname', $student->lastname, ['class' => 'form-control']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::Label('gender_id', 'Gender:') !!}
                        {!! Form::select('gender_id',$genders,$student->gender_id, ['class' => 'form-control']) !!}
                    </div>

                    <div class="form-group">

                        {!! Form::Label('joined_year', 'Joined year:') !!}
                        {!! Form::select('joined_year',$years,$student->joined_year, ['class' => 'form-control']) !!}

                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>

                <input type="hidden" value="{{csrf_token()}}" name="_token" />
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/students/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div><br />
    @endif
    @if(\Session::has('success'))
    <div class="alert alert-success">
        {{\Session::get('success')}}
    </div>
    @endif
    <div class="panel-heading">{{ __('school/common.list_students') }}</div>
    <div class="panel">

        <div class="panel-body bg-panel">

            <div class="col-sm-12 col-md-12 row">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="thead-light">
                        <th>{{ __('school/common.id') }}</th>
                        <th>{{ __('school/common.classroom') }}</th>
                        <th>{{ __('school/common.teachername') }}</th>
                        <th>{{ __('school/common.firstname') }}</th>
                        <th>{{ __('school/common.lastname') }}</th>
                        <th>{{ __('school/common.gender') }}</th>
                        <th>{{ __('school/common.joinedyear') }}</th>
                        <th>{{ __('school/common.createdat') }}</th>
                        <th colspan="2">{{ __('school/common.action') }}</th>            
                        </thead>
                        <tbody>


                            @forelse($students as $student)


                            <tr class="data-row">
                                <!--<td><a href="{{route('students.show', $student->id )}}">{{ $student->id}}</a></td>-->
                                <td>{{ $student->id }}</td>
                                <td>{{ isset($student->classRoom->name) ? $student->classRoom->name : null }}</td>
                                <td>{{ isset($student->teacher->name) ? $student->teacher->name: null }}</td>
                                <td>{{ $student->firstname }}</td>
                                <td>{{ $student->lastname }}</td>
                                <td>{{ isset($student->gender->name) ? $student->gender->name :null }}</td>
                                <td>{{ $student->joined_year }}</td>
                                <td>{{ \Carbon\Carbon::parse($student->created_at)->setTimezone('GMT+8')->format('Y-m-d H:i:s') }}</td>
                                <td> <a href="{{ url('students/'.$student->id . '/edit') }}" class="btn btn-default">{{ __('school/common.action_edit') }}</a>
                                <td>
                                    <form action="{{action('StudentController@destroy', $student->id)}}" method="post">
                                        {{csrf_field()}}
                                        <input name="_method" type="hidden" value="DELETE"/>
                                        <button class="btn btn-danger" type="submit">{{ __('school/common.action_delete') }}</button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="5">{{ __('school/common.no_records_found') }}</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {!! $students->links() !!}
                </div>
            </div>

            <div class="col-sm-12 col-md-12 row">
                <div class="button-div">
                    <a class="btn btn-primary" href="{{ url('/students/create') }}">{{ __('school/common.button_create') }}</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/students/upload.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div><br />
    @endif
    <div class="panel-heading">{{ __('school/common.file_import') }}</div>
    <div class="panel">

        <div class="panel-body bg-panel">
            <div class="row">

                <div class="panel-body">

                    <form class="form-horizontal" method="POST" action="{{ route('upload') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('csv_file') ? ' has-error' : '' }}">
                            <label for="csv_file" class="col-md-4 control-label">{{ __('school/common.file_import') }}</label>

                            <div class="col-md-6">
                                <input id="csv_file" type="file" class="form-control" name="csv_file" required>

                                @if ($errors->has('csv_file'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('csv_file') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>



                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
    @endsection